import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Marketing, Investment, Dataquality } from "../components";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex p-20 w-auto gap-4">
        <div className=" flex flex-col gap-7">
          <Dataquality />
          <div className="flex flex-row gap-7">
            <Marketing></Marketing>
            <Investment></Investment>
            <Investment></Investment>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
